title: Withney Guilherme
description: Meu site pessoal
remote_theme: wguilherme/jekyll-minimal-synthwave

# Social links
github_username: wguilherme
linkedin_username: wguilherme
twitter_username: wguilherme

# Google Analytics
google_analytics: # seu c√≥digo do GA aqui se desejar

# Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Theme Configuration
theme_config:
  style: hacker # ou 'hacker' para o outro estilo
  appearance: "auto" # pode ser "light", "dark" ou "auto"
  back_home_text: ".."
